version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my-postgres-container2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'changeme'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'changeme'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
