version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=adminpass
      - MONGO_INITDB_DATABASE=usuarios

  java_app:
    container_name: crudproduct_app
    image: crudproduct_app:1.0.0
    build: .
    ports:
      - "8081:8081"
    environment:
      - MONGO_HOST=mongodb
#      - MONGO_USER=admin
#      - MONGO_PASS=adminpass
      - MONGO_PORT=27017
      - MONGO_DB=usuarios
    depends_on:
      - mongodb


